# 服务配置 http配置和GRPC接口配置
server:
  port: 18080
  compression:
    enabled: true
    mime-types: application/json,application/octet-stream

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    org.springframework.web: ERROR

{grpyml}

app-properties:
  token-key: token
  http-api-path: /api/**

# spring配置
spring:
  application:
    name: GrpcFramework-Server-APP
  aop:
    auto: true
    proxy-target-class: true
  {persistenceyml}

{restful}